[wip] brew recycler core adapter
carrot/recycler-core pull request #47
Opened 2016-09-30 22:42 UTC by roideuniverse

2016-10-18 15:26 UTC, BrandonRomano commented on recyclercore-compiler/src/main/java/com/carrotcreative/recyclercore/compiler/ClassUtil.java
> +        return type.getQualifiedName().toString().substring(packageLen).replace('.', '$');
Why `.replace('.', '$');` here?

2016-10-18 15:27 UTC, BrandonRomano commented
Super solid/clean man 👍 👍

2016-10-18 15:47 UTC, roideuniverse commented on recyclercore-compiler/src/main/java/com/carrotcreative/recyclercore/compiler/ClassUtil.java
> +        return type.getQualifiedName().toString().substring(packageLen).replace('.', '$');
Good catch, I believe it was for Inner classes. For example 
```
package app.ui
MainActivity {
  @RCModel
  TestModel {
  }
}
```
In this case the package would be `app.ui` and the class will be `MainActivity.TestModel` which this util function would change it into `MainActivity$TestActivity`

I just tried it and hit a roadblock, will need to test this and get back to you.

2016-10-18 15:48 UTC, BrandonRomano commented on recyclercore-compiler/src/main/java/com/carrotcreative/recyclercore/compiler/ClassUtil.java
> +        return type.getQualifiedName().toString().substring(packageLen).replace('.', '$');
Sure thing... I'll assign this PR back to you until then!

2016-10-26 15:36 UTC, BrandonRomano approved these changes

2016-11-04 20:02 UTC, asolis90 requested changes
Looks good to merge after fixing some minor comments

2016-11-04 20:02 UTC, asolis90 commented on recyclercore-compiler/src/main/java/com/carrotcreative/recyclercore/compiler/PreProcessorHelper.java
> +    private Filer mFiler;
mFiler and mElements are not being used here

2016-11-04 20:02 UTC, asolis90 commented on recyclercore-compiler/src/main/java/com/carrotcreative/recyclercore/compiler/ModelDetails.java
> +        catch(MirroredTypeException ex)
Could you add a comment here that we are getting the controller's canonical name in the MirroredException

2016-11-08 19:52 UTC, roideuniverse commented on recyclercore-compiler/src/main/java/com/carrotcreative/recyclercore/compiler/ModelDetails.java
> +        catch(MirroredTypeException ex)
Added as method comment.

2016-11-16 17:16 UTC, asolis90 approved these changes

2016-11-21 20:15 UTC, roideuniverse commented
I no longer have access to merge this. Please merge.

2016-12-17 00:15 UTC, tinder-ksaurabh commented
@BrandonRomano @asolis90 Guys mere this PR!

2016-12-19 01:45 UTC, BrandonRomano commented
Sorry about that @tinder-ksaurabh -- forgot to merge this in.. Doing it now 🚀

2016-12-19 01:45 UTC, merged

2016-12-19 02:05 UTC, roideuniverse commented
Thanks @BrandonRomano :+1:

2016-12-19 02:12 UTC, BrandonRomano commented
You got it 👌 sorry it took so long 😬 .

Will get you access to this repo Monday.