Update example
carrot/recycler-core pull request #51
Opened 2016-10-10 16:13 UTC by roideuniverse

2016-10-26 15:36 UTC, BrandonRomano approved these changes
Awesome 👍

2016-11-03 19:37 UTC, asolis90 requested changes

2016-11-03 19:37 UTC, asolis90 commented on README.md
> +@RCModel(controller = UserListRecyclerController.class)
should be UserController  or the controller should of be named UserListRecyclerController below 👀

2016-11-04 20:02 UTC, asolis90 approved these changes

2016-11-05 01:08 UTC, merged